
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: greater_development

test:
  <<: *default
  database: greater_test

production:
  <<: *default
  database: greater_production
  username: greater
  password: <%= ENV['SAMPLE_DATABASE_PASSWORD'] %>
